// Package identity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package identity

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthExchangeResponseTokenType.
const (
	Bearer AuthExchangeResponseTokenType = "Bearer"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// AuthExchangeRequest defines model for AuthExchangeRequest.
type AuthExchangeRequest struct {
	// ExternalUserId User ID as known by the customer platform
	ExternalUserId string `json:"external_user_id"`

	// Provider Identifier of the customer platform or auth provider
	Provider string `json:"provider"`

	// Tenant Optional tenant context
	Tenant *string `json:"tenant,omitempty"`
}

// AuthExchangeResponse defines model for AuthExchangeResponse.
type AuthExchangeResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds
	ExpiresIn int32 `json:"expires_in"`

	// PlatformUserId Proteon platform user ID (stable across exchanges)
	PlatformUserId openapi_types.UUID            `json:"platform_user_id"`
	TokenType      AuthExchangeResponseTokenType `json:"token_type"`
}

// AuthExchangeResponseTokenType defines model for AuthExchangeResponse.TokenType.
type AuthExchangeResponseTokenType string

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable machine-readable error code
	Code string `json:"code"`

	// Details Optional structured error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable message
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`

	// RequestId Correlation id for troubleshooting (propagate from gateway if present)
	RequestId *string `json:"request_id,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service *string              `json:"service,omitempty"`
	Status  HealthResponseStatus `json:"status"`
	Version *string              `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Jwk defines model for Jwk.
type Jwk struct {
	Alg                  *string                `json:"alg,omitempty"`
	Kid                  string                 `json:"kid"`
	Kty                  string                 `json:"kty"`
	Use                  *string                `json:"use,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// JwksResponse defines model for JwksResponse.
type JwksResponse struct {
	Keys []Jwk `json:"keys"`
}

// PlatformIdentityResponse defines model for PlatformIdentityResponse.
type PlatformIdentityResponse struct {
	CreatedAt      time.Time          `json:"created_at"`
	ExternalUserId string             `json:"external_user_id"`
	PlatformUserId openapi_types.UUID `json:"platform_user_id"`
	Provider       string             `json:"provider"`
	Tenant         *string            `json:"tenant,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PostV1AuthExchangeJSONRequestBody defines body for PostV1AuthExchange for application/json ContentType.
type PostV1AuthExchangeJSONRequestBody = AuthExchangeRequest

// Getter for additional properties for Jwk. Returns the specified
// element and whether it was found
func (a Jwk) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Jwk
func (a *Jwk) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Jwk to handle AdditionalProperties
func (a *Jwk) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["alg"]; found {
		err = json.Unmarshal(raw, &a.Alg)
		if err != nil {
			return fmt.Errorf("error reading 'alg': %w", err)
		}
		delete(object, "alg")
	}

	if raw, found := object["kid"]; found {
		err = json.Unmarshal(raw, &a.Kid)
		if err != nil {
			return fmt.Errorf("error reading 'kid': %w", err)
		}
		delete(object, "kid")
	}

	if raw, found := object["kty"]; found {
		err = json.Unmarshal(raw, &a.Kty)
		if err != nil {
			return fmt.Errorf("error reading 'kty': %w", err)
		}
		delete(object, "kty")
	}

	if raw, found := object["use"]; found {
		err = json.Unmarshal(raw, &a.Use)
		if err != nil {
			return fmt.Errorf("error reading 'use': %w", err)
		}
		delete(object, "use")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Jwk to handle AdditionalProperties
func (a Jwk) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Alg != nil {
		object["alg"], err = json.Marshal(a.Alg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'alg': %w", err)
		}
	}

	object["kid"], err = json.Marshal(a.Kid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kid': %w", err)
	}

	object["kty"], err = json.Marshal(a.Kty)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kty': %w", err)
	}

	if a.Use != nil {
		object["use"], err = json.Marshal(a.Use)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'use': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1WellKnownJwks request
	GetV1WellKnownJwks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1AuthExchangeWithBody request with any body
	PostV1AuthExchangeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1AuthExchange(ctx context.Context, body PostV1AuthExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Health request
	GetV1Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1UsersUserId request
	GetV1UsersUserId(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1WellKnownJwks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1WellKnownJwksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthExchangeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthExchangeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthExchange(ctx context.Context, body PostV1AuthExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthExchangeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1HealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1UsersUserId(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1UsersUserIdRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1WellKnownJwksRequest generates requests for GetV1WellKnownJwks
func NewGetV1WellKnownJwksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/.well-known/jwks.json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1AuthExchangeRequest calls the generic PostV1AuthExchange builder with application/json body
func NewPostV1AuthExchangeRequest(server string, body PostV1AuthExchangeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1AuthExchangeRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1AuthExchangeRequestWithBody generates requests for PostV1AuthExchange with any type of body
func NewPostV1AuthExchangeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/exchange")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetV1HealthRequest generates requests for GetV1Health
func NewGetV1HealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1UsersUserIdRequest generates requests for GetV1UsersUserId
func NewGetV1UsersUserIdRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "userId", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1WellKnownJwksWithResponse request
	GetV1WellKnownJwksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WellKnownJwksResponse, error)

	// PostV1AuthExchangeWithBodyWithResponse request with any body
	PostV1AuthExchangeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthExchangeResponse, error)

	PostV1AuthExchangeWithResponse(ctx context.Context, body PostV1AuthExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthExchangeResponse, error)

	// GetV1HealthWithResponse request
	GetV1HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1HealthResponse, error)

	// GetV1UsersUserIdWithResponse request
	GetV1UsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1UsersUserIdResponse, error)
}

type GetV1WellKnownJwksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JwksResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetV1WellKnownJwksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1WellKnownJwksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1AuthExchangeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AuthExchangeResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON429      *TooManyRequests
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r PostV1AuthExchangeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1AuthExchangeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1HealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetV1HealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1HealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1UsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PlatformIdentityResponse
	JSON404      *NotFound
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetV1UsersUserIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1UsersUserIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1WellKnownJwksWithResponse request returning *GetV1WellKnownJwksResponse
func (c *ClientWithResponses) GetV1WellKnownJwksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WellKnownJwksResponse, error) {
	rsp, err := c.GetV1WellKnownJwks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1WellKnownJwksResponse(rsp)
}

// PostV1AuthExchangeWithBodyWithResponse request with arbitrary body returning *PostV1AuthExchangeResponse
func (c *ClientWithResponses) PostV1AuthExchangeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthExchangeResponse, error) {
	rsp, err := c.PostV1AuthExchangeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthExchangeResponse(rsp)
}

func (c *ClientWithResponses) PostV1AuthExchangeWithResponse(ctx context.Context, body PostV1AuthExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthExchangeResponse, error) {
	rsp, err := c.PostV1AuthExchange(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthExchangeResponse(rsp)
}

// GetV1HealthWithResponse request returning *GetV1HealthResponse
func (c *ClientWithResponses) GetV1HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1HealthResponse, error) {
	rsp, err := c.GetV1Health(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1HealthResponse(rsp)
}

// GetV1UsersUserIdWithResponse request returning *GetV1UsersUserIdResponse
func (c *ClientWithResponses) GetV1UsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1UsersUserIdResponse, error) {
	rsp, err := c.GetV1UsersUserId(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1UsersUserIdResponse(rsp)
}

// ParseGetV1WellKnownJwksResponse parses an HTTP response from a GetV1WellKnownJwksWithResponse call
func ParseGetV1WellKnownJwksResponse(rsp *http.Response) (*GetV1WellKnownJwksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1WellKnownJwksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JwksResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostV1AuthExchangeResponse parses an HTTP response from a PostV1AuthExchangeWithResponse call
func ParsePostV1AuthExchangeResponse(rsp *http.Response) (*PostV1AuthExchangeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1AuthExchangeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuthExchangeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1HealthResponse parses an HTTP response from a GetV1HealthWithResponse call
func ParseGetV1HealthResponse(rsp *http.Response) (*GetV1HealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1HealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1UsersUserIdResponse parses an HTTP response from a GetV1UsersUserIdWithResponse call
func ParseGetV1UsersUserIdResponse(rsp *http.Response) (*GetV1UsersUserIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1UsersUserIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PlatformIdentityResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
