// Package identity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package identity

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for TokenPairResponseTokenType.
const (
	Bearer TokenPairResponseTokenType = "Bearer"
)

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable machine-readable error code
	Code string `json:"code"`

	// Details Optional structured error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable message
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`

	// RequestId Correlation id for troubleshooting (propagate from gateway if present)
	RequestId *string `json:"request_id,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service *string              `json:"service,omitempty"`
	Status  HealthResponseStatus `json:"status"`
	Version *string              `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Jwk defines model for Jwk.
type Jwk struct {
	Alg                  *string                `json:"alg,omitempty"`
	Kid                  string                 `json:"kid"`
	Kty                  string                 `json:"kty"`
	Use                  *string                `json:"use,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// JwksResponse defines model for JwksResponse.
type JwksResponse struct {
	Keys []Jwk `json:"keys"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string  `json:"login"`
	Password string  `json:"password"`
	Tenant   *string `json:"tenant,omitempty"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Scopes    *[]string `json:"scopes,omitempty"`
	SessionId *string   `json:"session_id,omitempty"`
	Sub       string    `json:"sub"`
	Tenant    string    `json:"tenant"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// TokenPairResponse defines model for TokenPairResponse.
type TokenPairResponse struct {
	AccessToken  string                     `json:"access_token"`
	ExpiresIn    int32                      `json:"expires_in"`
	RefreshToken string                     `json:"refresh_token"`
	Scope        *string                    `json:"scope,omitempty"`
	SessionId    *string                    `json:"session_id,omitempty"`
	TokenType    TokenPairResponseTokenType `json:"token_type"`
}

// TokenPairResponseTokenType defines model for TokenPairResponse.TokenType.
type TokenPairResponseTokenType string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1AuthLogoutJSONRequestBody defines body for PostV1AuthLogout for application/json ContentType.
type PostV1AuthLogoutJSONRequestBody = LogoutRequest

// PostV1AuthRefreshJSONRequestBody defines body for PostV1AuthRefresh for application/json ContentType.
type PostV1AuthRefreshJSONRequestBody = RefreshRequest

// Getter for additional properties for Jwk. Returns the specified
// element and whether it was found
func (a Jwk) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Jwk
func (a *Jwk) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Jwk to handle AdditionalProperties
func (a *Jwk) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["alg"]; found {
		err = json.Unmarshal(raw, &a.Alg)
		if err != nil {
			return fmt.Errorf("error reading 'alg': %w", err)
		}
		delete(object, "alg")
	}

	if raw, found := object["kid"]; found {
		err = json.Unmarshal(raw, &a.Kid)
		if err != nil {
			return fmt.Errorf("error reading 'kid': %w", err)
		}
		delete(object, "kid")
	}

	if raw, found := object["kty"]; found {
		err = json.Unmarshal(raw, &a.Kty)
		if err != nil {
			return fmt.Errorf("error reading 'kty': %w", err)
		}
		delete(object, "kty")
	}

	if raw, found := object["use"]; found {
		err = json.Unmarshal(raw, &a.Use)
		if err != nil {
			return fmt.Errorf("error reading 'use': %w", err)
		}
		delete(object, "use")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Jwk to handle AdditionalProperties
func (a Jwk) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Alg != nil {
		object["alg"], err = json.Marshal(a.Alg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'alg': %w", err)
		}
	}

	object["kid"], err = json.Marshal(a.Kid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kid': %w", err)
	}

	object["kty"], err = json.Marshal(a.Kty)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kty': %w", err)
	}

	if a.Use != nil {
		object["use"], err = json.Marshal(a.Use)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'use': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1WellKnownJwks request
	GetV1WellKnownJwks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1AuthLoginWithBody request with any body
	PostV1AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1AuthLogin(ctx context.Context, body PostV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1AuthLogoutWithBody request with any body
	PostV1AuthLogoutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1AuthLogout(ctx context.Context, body PostV1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1AuthRefreshWithBody request with any body
	PostV1AuthRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1AuthRefresh(ctx context.Context, body PostV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Health request
	GetV1Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Me request
	GetV1Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1WellKnownJwks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1WellKnownJwksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthLogin(ctx context.Context, body PostV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthLogoutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthLogoutRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthLogout(ctx context.Context, body PostV1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthLogoutRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthRefreshRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1AuthRefresh(ctx context.Context, body PostV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1AuthRefreshRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1HealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1MeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1WellKnownJwksRequest generates requests for GetV1WellKnownJwks
func NewGetV1WellKnownJwksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/.well-known/jwks.json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1AuthLoginRequest calls the generic PostV1AuthLogin builder with application/json body
func NewPostV1AuthLoginRequest(server string, body PostV1AuthLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1AuthLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1AuthLoginRequestWithBody generates requests for PostV1AuthLogin with any type of body
func NewPostV1AuthLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostV1AuthLogoutRequest calls the generic PostV1AuthLogout builder with application/json body
func NewPostV1AuthLogoutRequest(server string, body PostV1AuthLogoutJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1AuthLogoutRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1AuthLogoutRequestWithBody generates requests for PostV1AuthLogout with any type of body
func NewPostV1AuthLogoutRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/logout")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostV1AuthRefreshRequest calls the generic PostV1AuthRefresh builder with application/json body
func NewPostV1AuthRefreshRequest(server string, body PostV1AuthRefreshJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1AuthRefreshRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1AuthRefreshRequestWithBody generates requests for PostV1AuthRefresh with any type of body
func NewPostV1AuthRefreshRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetV1HealthRequest generates requests for GetV1Health
func NewGetV1HealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1MeRequest generates requests for GetV1Me
func NewGetV1MeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1WellKnownJwksWithResponse request
	GetV1WellKnownJwksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WellKnownJwksResponse, error)

	// PostV1AuthLoginWithBodyWithResponse request with any body
	PostV1AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthLoginResponse, error)

	PostV1AuthLoginWithResponse(ctx context.Context, body PostV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthLoginResponse, error)

	// PostV1AuthLogoutWithBodyWithResponse request with any body
	PostV1AuthLogoutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthLogoutResponse, error)

	PostV1AuthLogoutWithResponse(ctx context.Context, body PostV1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthLogoutResponse, error)

	// PostV1AuthRefreshWithBodyWithResponse request with any body
	PostV1AuthRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthRefreshResponse, error)

	PostV1AuthRefreshWithResponse(ctx context.Context, body PostV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthRefreshResponse, error)

	// GetV1HealthWithResponse request
	GetV1HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1HealthResponse, error)

	// GetV1MeWithResponse request
	GetV1MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1MeResponse, error)
}

type GetV1WellKnownJwksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JwksResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetV1WellKnownJwksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1WellKnownJwksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1AuthLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenPairResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON429      *TooManyRequests
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r PostV1AuthLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1AuthLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1AuthLogoutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON429      *TooManyRequests
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r PostV1AuthLogoutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1AuthLogoutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1AuthRefreshResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenPairResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON429      *TooManyRequests
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r PostV1AuthRefreshResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1AuthRefreshResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1HealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetV1HealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1HealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1MeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MeResponse
	JSON401      *Unauthorized
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetV1MeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1MeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1WellKnownJwksWithResponse request returning *GetV1WellKnownJwksResponse
func (c *ClientWithResponses) GetV1WellKnownJwksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WellKnownJwksResponse, error) {
	rsp, err := c.GetV1WellKnownJwks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1WellKnownJwksResponse(rsp)
}

// PostV1AuthLoginWithBodyWithResponse request with arbitrary body returning *PostV1AuthLoginResponse
func (c *ClientWithResponses) PostV1AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthLoginResponse, error) {
	rsp, err := c.PostV1AuthLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthLoginResponse(rsp)
}

func (c *ClientWithResponses) PostV1AuthLoginWithResponse(ctx context.Context, body PostV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthLoginResponse, error) {
	rsp, err := c.PostV1AuthLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthLoginResponse(rsp)
}

// PostV1AuthLogoutWithBodyWithResponse request with arbitrary body returning *PostV1AuthLogoutResponse
func (c *ClientWithResponses) PostV1AuthLogoutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthLogoutResponse, error) {
	rsp, err := c.PostV1AuthLogoutWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthLogoutResponse(rsp)
}

func (c *ClientWithResponses) PostV1AuthLogoutWithResponse(ctx context.Context, body PostV1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthLogoutResponse, error) {
	rsp, err := c.PostV1AuthLogout(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthLogoutResponse(rsp)
}

// PostV1AuthRefreshWithBodyWithResponse request with arbitrary body returning *PostV1AuthRefreshResponse
func (c *ClientWithResponses) PostV1AuthRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1AuthRefreshResponse, error) {
	rsp, err := c.PostV1AuthRefreshWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthRefreshResponse(rsp)
}

func (c *ClientWithResponses) PostV1AuthRefreshWithResponse(ctx context.Context, body PostV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1AuthRefreshResponse, error) {
	rsp, err := c.PostV1AuthRefresh(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1AuthRefreshResponse(rsp)
}

// GetV1HealthWithResponse request returning *GetV1HealthResponse
func (c *ClientWithResponses) GetV1HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1HealthResponse, error) {
	rsp, err := c.GetV1Health(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1HealthResponse(rsp)
}

// GetV1MeWithResponse request returning *GetV1MeResponse
func (c *ClientWithResponses) GetV1MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1MeResponse, error) {
	rsp, err := c.GetV1Me(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1MeResponse(rsp)
}

// ParseGetV1WellKnownJwksResponse parses an HTTP response from a GetV1WellKnownJwksWithResponse call
func ParseGetV1WellKnownJwksResponse(rsp *http.Response) (*GetV1WellKnownJwksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1WellKnownJwksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JwksResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostV1AuthLoginResponse parses an HTTP response from a PostV1AuthLoginWithResponse call
func ParsePostV1AuthLoginResponse(rsp *http.Response) (*PostV1AuthLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1AuthLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenPairResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostV1AuthLogoutResponse parses an HTTP response from a PostV1AuthLogoutWithResponse call
func ParsePostV1AuthLogoutResponse(rsp *http.Response) (*PostV1AuthLogoutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1AuthLogoutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostV1AuthRefreshResponse parses an HTTP response from a PostV1AuthRefreshWithResponse call
func ParsePostV1AuthRefreshResponse(rsp *http.Response) (*PostV1AuthRefreshResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1AuthRefreshResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenPairResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1HealthResponse parses an HTTP response from a GetV1HealthWithResponse call
func ParseGetV1HealthResponse(rsp *http.Response) (*GetV1HealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1HealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1MeResponse parses an HTTP response from a GetV1MeWithResponse call
func ParseGetV1MeResponse(rsp *http.Response) (*GetV1MeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1MeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
