#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   tools/scripts/create-service-structure.sh identity
#
# Creates a new service under services/<service>/ as an independent Go module.

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <service-name>"
  exit 1
fi

SERVICE="$1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

MODULE_PREFIX="github.com/woffVienna/proteon-cursor"
ROOT="${REPO_ROOT}/services/${SERVICE}"

if [[ -e "$ROOT" ]]; then
  echo "Error: '${ROOT}' already exists."
  exit 1
fi

# Copy service Makefile template
TEMPLATE_MAKEFILE="${SCRIPT_DIR}/Makefile"

if [[ ! -f "${TEMPLATE_MAKEFILE}" ]]; then
  echo "Error: Makefile template not found next to script at ${TEMPLATE_MAKEFILE}"
  exit 1
fi

# --- folders: minimal structure (add db, nats, platform, etc. when needed) ---
mkdir -p "${ROOT}/api"
mkdir -p "${ROOT}/cmd/${SERVICE}"
mkdir -p "${ROOT}/internal/adapters/http/generated/server"
mkdir -p "${ROOT}/internal/application/interfaces"
mkdir -p "${ROOT}/internal/domain"

# --- non-go placeholder files ---
touch "${ROOT}/api/openapi.yml"

# codegen config for server (client deferred)
cat > "${ROOT}/api/oapi-codegen.server.yml" <<EOF
package: server
output: internal/adapters/http/generated/server/openapi.gen.go

generate:
  models: true
  chi-server: true
  strict-server: true
EOF

touch "${ROOT}/README.md"

# --- Go files: minimal stubs ---

# cmd/<service>/main.go
cat > "${ROOT}/cmd/${SERVICE}/main.go" <<EOF
package main

import "log"

func main() {
	log.Println("${SERVICE} service starting...")
}
EOF

# internal/adapters/http/server.go
cat > "${ROOT}/internal/adapters/http/server.go" <<'EOF'
package http

// Package http contains the HTTP adapter (routing, middleware, handlers).
EOF

# --- initialize go module (go.sum generated by go tooling) ---
(
  cd "${ROOT}"
  go mod init "${MODULE_PREFIX}/services/${SERVICE}"
)

cp "${TEMPLATE_MAKEFILE}" "${ROOT}/Makefile"

echo "Created service structure at: ${ROOT}"
echo "Initialized Go module: ${MODULE_PREFIX}/services/${SERVICE}"
echo "Next steps:"
echo "  1) Add minimal OpenAPI to api/openapi.yml"
echo "  2) From repo root: make generate (or from service: make generate)"
echo "  3) Then: (cd ${ROOT} && go mod tidy) to pull chi + oapi-codegen runtime deps"
