#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   tools/scripts/create-service-structure.sh identity
#
# Creates a new service under services/<service>/ as an independent Go module.

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <service-name>"
  exit 1
fi

SERVICE="$1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

MODULE_PREFIX="github.com/woffVienna/proteon-cursor"
ROOT="${REPO_ROOT}/services/${SERVICE}"

if [[ -e "$ROOT" ]]; then
  echo "Error: '${ROOT}' already exists."
  exit 1
fi

# Copy service Makefile template
TEMPLATE_MAKEFILE="${SCRIPT_DIR}/Makefile"

if [[ ! -f "${TEMPLATE_MAKEFILE}" ]]; then
  echo "Error: Makefile template not found next to script at ${TEMPLATE_MAKEFILE}"
  exit 1
fi

# --- folders (folders first) ---
mkdir -p "${ROOT}/api/.generated"
mkdir -p "${ROOT}/api/events"
mkdir -p "${ROOT}/api/schemas"

mkdir -p "${ROOT}/cmd/${SERVICE}"

mkdir -p "${ROOT}/internal/adapters/db/migrations"
mkdir -p "${ROOT}/internal/adapters/db/postgres"

mkdir -p "${ROOT}/internal/adapters/http/generated/server"
mkdir -p "${ROOT}/internal/adapters/http/handlers"
mkdir -p "${ROOT}/internal/adapters/http/mapping"
mkdir -p "${ROOT}/internal/adapters/http/middleware"

mkdir -p "${ROOT}/internal/adapters/nats/consumer"
mkdir -p "${ROOT}/internal/adapters/nats/mapping"
mkdir -p "${ROOT}/internal/adapters/nats/publisher"

mkdir -p "${ROOT}/internal/application/dto"
mkdir -p "${ROOT}/internal/application/interfaces"
mkdir -p "${ROOT}/internal/application/services"

mkdir -p "${ROOT}/internal/domain/model"
mkdir -p "${ROOT}/internal/domain/rules"

mkdir -p "${ROOT}/internal/platform/buildinfo"
mkdir -p "${ROOT}/internal/platform/health"
mkdir -p "${ROOT}/internal/platform/shutdown"

mkdir -p "${ROOT}/test/contract"
mkdir -p "${ROOT}/test/integration"

# --- non-go placeholder files ---
touch "${ROOT}/api/openapi.yml"

# codegen config for server (client deferred)
cat > "${ROOT}/api/oapi-codegen.server.yml" <<EOF
package: server
output: internal/adapters/http/generated/server/openapi.gen.go

generate:
  models: true
  chi-server: true
  strict-server: true
EOF

# Keep empty directories in git (optional)
touch "${ROOT}/api/events/.keep"
touch "${ROOT}/api/schemas/.keep"
touch "${ROOT}/internal/domain/model/.keep"
touch "${ROOT}/internal/domain/rules/.keep"
touch "${ROOT}/internal/platform/buildinfo/.keep"
touch "${ROOT}/internal/platform/health/.keep"
touch "${ROOT}/internal/platform/shutdown/.keep"
touch "${ROOT}/test/contract/.keep"
touch "${ROOT}/test/integration/.keep"

touch "${ROOT}/README.md"

# --- Go files: create valid package stubs (so go test/lint succeeds) ---

# cmd/<service>/main.go
cat > "${ROOT}/cmd/${SERVICE}/main.go" <<EOF
package main

import "log"

func main() {
	log.Println("${SERVICE} service starting...")
}
EOF

# internal/adapters/db/db.go
cat > "${ROOT}/internal/adapters/db/db.go" <<'EOF'
package db

// Package db contains database adapter wiring and helpers.
// Concrete implementations live in subpackages (e.g. postgres).
EOF

# internal/adapters/http/server.go
cat > "${ROOT}/internal/adapters/http/server.go" <<'EOF'
package http

// Package http contains the HTTP adapter (routing, middleware, handlers).
EOF

# internal/adapters/nats/nats.go
cat > "${ROOT}/internal/adapters/nats/nats.go" <<'EOF'
package nats

// Package nats contains NATS adapter wiring (publishers/consumers).
EOF

# internal/domain/errors.go
cat > "${ROOT}/internal/domain/errors.go" <<'EOF'
package domain

// Domain errors should be typed and mapped to transport errors in adapters.
EOF

# internal/domain/events.go
cat > "${ROOT}/internal/domain/events.go" <<'EOF'
package domain

// Domain events (optional): emitted by domain logic and published by application/adapters.
EOF

# --- initialize go module (go.sum generated by go tooling) ---
(
  cd "${ROOT}"
  go mod init "${MODULE_PREFIX}/services/${SERVICE}"
)

cp "${TEMPLATE_MAKEFILE}" "${ROOT}/Makefile"

echo "Created service structure at: ${ROOT}"
echo "Initialized Go module: ${MODULE_PREFIX}/services/${SERVICE}"
echo "Next steps:"
echo "  1) Add minimal OpenAPI to api/openapi.yml"
echo "  2) From repo root: make generate (or from service: make generate)"
echo "  3) Then: (cd ${ROOT} && go mod tidy) to pull chi + oapi-codegen runtime deps"
